version: "2.1"

services:
  db:
    build: cassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 45s
      timeout: 10s
      retries: 10

  application:
    build: application
    links:
      - db
    depends_on:
      db:
        condition: service_healthy